baseURL = "https://openesmdata.org/"
languageCode = "en-us"
title = "openESM"
description = "open Experience Sampling Method (openESM) Database"
theme = "PaperMod"

# Enable search
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Menu items
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20  
  [[menu.main]]
    identifier = "datasets"
    name = "Datasets"
    url = "/datasets/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40
  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    url = "/docs/"
    weight = 50

  # Documentation submenu
  [[menu.docs]]
    identifier = "data"
    name = "Data"
    url = "/docs/data/"
    weight = 10
  [[menu.docs]]
    identifier = "technical"
    name = "Technical"
    url = "/docs/technical/"
    weight = 20
  [[menu.docs]]
    identifier = "packages"
    name = "Packages"
    url = "/docs/packages/"
    weight = 30
  [[menu.docs]]
    identifier = "contributing"
    name = "Contributing"
    url = "/docs/contributing/"
    weight = 40


# Enable HTML in Markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Parameters
[params]
  description = "Open Experience Sampling Method (ESM) Database"
  logo = "openesm_icon.svg"
  
  # Default theme (auto, light, dark)
  defaultTheme = "light"
  disableThemeToggle = true
  
  # Show code copy buttons
  ShowCodeCopyButtons = true
  
  # Show post reading time
  ShowReadingTime = false
  
  # Show table of contents
  ShowToc = false
  
  # Open TOC by default
  TocOpen = false

  # Don't show posts on home page
  mainSections = []

  [params.footer]
  text = "[Privacy](/openesm/privacy/) · [Source code](https://github.com/bsiepe/openesm) · Built by [Björn Siepe](https://bsiepe.github.io) "
  
  # Enable search
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
  
  # Custom CSS
  customCSS = ["assets/css/custom.css"]

